import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'category',
      label: '01 - Nervous System',
      link: {
        type: 'doc',
        id: 'nervous-system/intro'
      },
      items: [{type: 'autogenerated', dirName: '01-nervous-system'}],
    },
    {
      type: 'category',
      label: '02 - Digital Twin (Gazebo & Unity)',
      link: {
        type: 'doc',
        id: 'digital-twin-sim/intro'
      },
      items: [{type: 'autogenerated', dirName: '02-digital-twin-sim'}],
    },
    {
      type: 'category',
      label: '03 - The AI-Robot Brain (NVIDIA Isaac™)',
      link: {
        type: 'doc',
        id: 'isaac-sim-brain/intro'
      },
      items: [{type: 'autogenerated', dirName: '03-isaac-sim-brain'}],
    },
    {
      type: 'category',
      label: '04 - Vision-Language-Action (VLA)',
      link: {
        type: 'doc',
        id: 'vla-capstone/intro'
      },
      items: [{type: 'autogenerated', dirName: '04-vla-capstone'}],
    },
  ],
};

export default sidebars;